global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app1'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs: 
      - targets: ['localhost:9100']
